using System.Text.Json.Serialization;


namespace Kiyo9w.StoreMind.Core.Contracts;

/// <summary>
/// Nightly artifact generated by the planning agent
/// </summary>
[JsonSerializable(typeof(Plan))]
public record Plan(
    [property: JsonPropertyName("date")] string Date,
    [property: JsonPropertyName("assumptions")] IReadOnlyList<string> Assumptions,
    [property: JsonPropertyName("actions")] IReadOnlyList<Proposal> Actions,
    [property: JsonPropertyName("questions_for_manager")] IReadOnlyList<string> QuestionsForManager)
{
    [JsonPropertyName("plan_id")]
    public string PlanId { get; init; } = $"plan-{DateTime.UtcNow:yyyyMMdd}-{Guid.NewGuid():N}"[..24];

    [JsonPropertyName("generated_at")]
    public DateTimeOffset GeneratedAt { get; init; } = DateTimeOffset.UtcNow;

    [JsonPropertyName("model_used")]
    public string? ModelUsed { get; init; }

    /// <summary>
    /// Combined confidence score from all actions
    /// </summary>
    [JsonPropertyName("confidence_score")]
    public double ConfidenceScore => Actions.Count > 0 ? Actions.Average(a => a.Confidence) : 0.0;

    /// <summary>
    /// Checks dates and constraints. Returns (isValid, errorList).
    /// </summary>
    public (bool IsValid, IReadOnlyList<string> Errors) Validate()
    {
        var errors = new List<string>();

        if (!DateOnly.TryParseExact(Date, "yyyy-MM-dd", null, System.Globalization.DateTimeStyles.None, out _))
            errors.Add($"Invalid date format: '{Date}'. Expected YYYY-MM-DD.");

        if (Actions is null || Actions.Count == 0)
            errors.Add("Plan must contain at least one action.");
        else
        {
            for (var i = 0; i < Actions.Count; i++)
            {
                var action = Actions[i];
                if (!action.IsValid())
                    errors.Add($"Action[{i}] failed validation: SKU={action.Target?.Sku ?? "null"}");

                if (action.Evidence is null || action.Evidence.Count < 1)
                    errors.Add($"Action[{i}] missing required evidence pointer.");
            }
        }

        return (errors.Count == 0, errors);
    }

    /// <summary>
    /// Gets actions needing human approval that aren't processed yet
    /// </summary>
    public IEnumerable<Proposal> GetPendingApprovals() =>
        Actions.Where(a => a.RequiresManagerApproval && a.ApprovalState == ApprovalState.Pending);

    public decimal TotalExpectedMarginImpact() =>
        Actions.Sum(a => a.ExpectedImpact.MarginDelta);

    public decimal TotalExpectedWasteReduction() =>
        Actions.Sum(a => a.ExpectedImpact.WasteReduction);
}
